[workspace]
members = ["service/frontend", "service/server", "sim"]
default-members = ["service/frontend", "service/server"]
resolver = "3"

[[workspace.metadata.leptos]]
name = "refuel"
bin-package = "server"
lib-package = "frontend"
style-file = "service/style/main.scss"
assets-dir = "service/public"
end2end-dir = "service/end2end"
site-root = "target/site"

[workspace.package]
version = "0.2.0"
authors = ["Angelos Drossos"]
edition = "2024"

[workspace.dependencies]
# leptos
leptos = { version = "0.8.8" }
leptos_axum = { version = "0.8.6" }
leptos_meta = { version = "0.8.5" }
leptos_router = { version = "0.8.6" }
# axum and co.
axum = "0.8.4"
axum-macros = "0.5.0"
cfg-if = "1.0.3"
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
http = "1.3.1"
log = "0.4.27"
simple_logger = "5.0.0"
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["full"] }
tower = { version = "0.5.2", features = ["full"] }
tower-http = { version = "0.6.6", features = ["full"] }
wasm-bindgen = "=0.2.100"
# others
chrono = "0.4.41"
clap = { version = "4.2.46", features = ["derive"] }
serde = "1.0.219"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
