[package]
name = "refuel-server"
version.workspace = true
authors.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
clap = { version = "4.2.5", features = ["derive"] }
diesel = { version = "2.0.4", default-features = false, features = ["with-deprecated", "chrono", "sqlite"] }
dotenvy = "0.15.7"
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1.8.1"
reqwest = "0.11.16"
scraper = "0.15.0"
thiserror = "1.0.40"
tokio = { version = "1", features = ["full", "time"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
url = "2.3.1"
